export const productsTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_PRODUCTS_START: 'SET_PRODUCTS_START',
  FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
  ADD_NEW_PRODUCT_START: 'ADD_NEW_PRODUCT_START',
  DELETE_PRODUCT_START: 'DELETE_PRODUCT_START'
};

export default productsTypes;